# Generated by Django 3.1.4 on 2020-12-29 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ContactMe', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AboutMe',
            new_name='ContactMe',
        ),
    ]
