# Generated by Django 3.1.4 on 2020-12-30 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ContactMe', '0002_auto_20201229_1910'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactme',
            options={'verbose_name': 'Contact Me', 'verbose_name_plural': 'Contact Me'},
        ),
    ]
