# Generated by Django 3.1.4 on 2021-01-02 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ContactMe', '0003_auto_20201230_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactme',
            name='Job_title',
            field=models.CharField(max_length=50),
        ),
    ]
