# Generated by Django 3.1.4 on 2021-01-01 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_auto_20201229_1914'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ('-created_at',), 'verbose_name': 'Project', 'verbose_name_plural': 'Projects'},
        ),
    ]
