# Generated by Django 3.1.4 on 2021-01-02 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_auto_20210101_2247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image_file',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
