# Generated by Django 3.1.4 on 2020-12-28 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutMe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Job_title', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=50)),
                ('image_file', models.ImageField(null=True, upload_to='uploads/')),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('description', models.TextField(max_length=200)),
            ],
        ),
    ]
