# Generated by Django 3.1.4 on 2021-01-10 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AboutMe', '0003_skills'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timeline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
            ],
        ),
    ]
